# Generated by Django 4.0.3 on 2022-03-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_deck_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_deck', to='flashcard.deck'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
